server:
  port: 9006
spring:
  application:
    name: tensquare-whine
  data:
    mongodb:
      host: 192.168.85.132
      database: whinedb
  redis:
    host: 192.168.85.132
  rabbitmq:
    host: 192.168.85.132
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true