server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.85.132
eureka:
  client:
    service-url:
      defaultZone: http://192.168.85.132:6868/eureka
  instance:
    prefer-ip-address: true