server:
  port: 9010
spring:
  application:
    name: tensquare-friend
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.85.132:3306/tensquare_friend?characterEncoding=UTF8&useSSL=false
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
  rabbitmq: # this is for spring config bus
    host: 192.168.85.132
jwt:
  config:
    key: itcast
eureka:
  client:
    service-url:
      defaultZone: http://192.168.85.132:6868/eureka
  instance:
    prefer-ip-address: true
